export const INVESTOR_LIST_REQUEST = "INVESTOR_LIST_REQUEST";
export const INVESTOR_LIST_SUCCESS = "INVESTOR_LIST_SUCCESS";
export const INVESTOR_LIST_FAIL = "INVESTOR_LIST_FAIL";

export const INVESTOR_EDIT_REQUEST = "INVESTOR_EDIT_REQUEST";
export const INVESTOR_EDIT_SUCCESS = "INVESTOR_EDIT_SUCCESS";
export const INVESTOR_EDIT_FAIL = "INVESTOR_EDIT_FAIL";

export const INVESTOR_DELETE_REQUEST = "INVESTOR_DELETE_REQUEST";
export const INVESTOR_DELETE_SUCCESS = "INVESTOR_DELETE_SUCCESS";
export const INVESTOR_DELETE_FAIL = "INVESTOR_DELETE_FAIL";

export const INVESTOR_CREATE_REQUEST = "INVESTOR_CREATE_REQUEST";
export const INVESTOR_CREATE_SUCCESS = "INVESTOR_CREATE_SUCCESS";
export const INVESTOR_CREATE_FAIL = "INVESTOR_CREATE_FAIL";
export const INVESTOR_CREATE_RESET = "INVESTOR_CREATE_RESET";

export const INVESTOR_UPDATE_REQUEST = "INVESTOR_UPDATE_REQUEST";
export const INVESTOR_UPDATE_SUCCESS = "INVESTOR_UPDATE_SUCCESS";
export const INVESTOR_UPDATE_FAIL = "INVESTOR_UPDATE_FAIL";
export const INVESTOR_UPDATE_RESET = "INVESTOR_UPDATE_RESET";
