export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_SINGLE_REQUEST = "USER_SINGLE_REQUEST";
export const USER_SINGLE_SUCCESS = "USER_SINGLE_SUCCESS";
export const USER_SINGLE_FAIL = "USER_SINGLE_FAIL";
export const USER_SINGLE_RESET = "USER_SINGLE_RESET";
